services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    #environment:
    #  POSTGRES_PASSWORD: "local_password"
    env_file:
      - ../.env.development
    ports:
      #- "host:container"
      - 5432:5432
  #mailcatcher:
  #servico3:
