name: Hard Sync Repository

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1

      - name: Hard reset to upstream
        run: |
          git remote add upstream https://github.com/RodrigoMS/clone-tabnews.git
          git fetch upstream
          git reset --hard upstream/main
          git push origin main --force
